# This workflow is triggered on a push to the main branch
name: Build and Deploy to EKS

on:
  push:
    branches: ["main"]

# Environment variables available to all jobs and steps in the workflow
env:
  AWS_REGION: us-west-2 # Your AWS region
  ECR_REPOSITORY: nginx-custom # Your ECR repository name
  EKS_CLUSTER_NAME: eks-blueprint-cluster # Your EKS cluster name
  K8S_DEPLOYMENT_NAME: nginx-deployment # The name of the deployment in your K8s manifest
  K8S_CONTAINER_NAME: nginx-container # The name of the container in your K8s manifest

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Deploy new image to Amazon EKS
        uses: aws-actions/amazon-eks-set-image@v1
        with:
          cluster-name: ${{ env.EKS_CLUSTER_NAME }}
          deployment: ${{ env.K8S_DEPLOYMENT_NAME }}
          container: ${{ env.K8S_CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.digest }}
